[package]
name = "dingooemu-core"
description.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
crc32fast.workspace = true
bincode.workspace = true
lz4_flex.workspace = true
byteorder = "1"
image.workspace = true
rodio = { workspace = true, optional = true }
cranelift = { workspace = true, optional = true }
cranelift-jit = { workspace = true, optional = true }
cranelift-module = { workspace = true, optional = true }
cranelift-native = { workspace = true, optional = true }

[dev-dependencies]
env_logger.workspace = true
cargo-husky = { version = "=1.5.0", default-features = false, features = ["precommit-hook", "run-cargo-fmt", "run-cargo-clippy"] }

[features]
standalone = ["dep:rodio"]
jit = [
    "dep:cranelift",
    "dep:cranelift-jit",
    "dep:cranelift-module",
    "dep:cranelift-native",
]
