sonar.projectKey=AloysHF_DingooEmu
sonar.projectName=DingooEmu
sonar.organization=aloyshf-github

sonar.sources=crates
sonar.exclusions=**/target/**
sonar.sourceEncoding=UTF-8

sonar.rust.cobertura.reportPaths=coverage/cobertura.xml
